-- AlterTable
ALTER TABLE `Column` ADD COLUMN `oPrice` DECIMAL(65, 30) NULL,
    ADD COLUMN `price` DECIMAL(65, 30) NULL,
    ADD COLUMN `url` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `Course` ADD COLUMN `url` VARCHAR(191) NULL;
